name:                evie
version:             0.0.5
github:              "state-machine-io/evie"
license:             "Apache-2.0"
author:              "State Machine Pty Ltd"
maintainer:          "developers@statemachine.io"
copyright:           "2019 State Machine Pty Ltd"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/state-machine-io/evie#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -fno-warn-deprecations
    - -fprint-potential-instances
    - -fwarn-unused-imports
    - -fwarn-unused-binds
    - -fwarn-tabs
  default-extensions:
    - OverloadedStrings
    - TypeOperators
    - DataKinds
    - RecordWildCards
    - DeriveGeneric
  dependencies:
    - servant-server
    - wai
    - warp
    - open-browser
    - optparse-generic
    - bytestring
    - text
    - aeson
    - mtl
    - resource-pool
    - postgresql-simple
    - ginger
    - unordered-containers
    - http-media
    - sqlite-simple
    - neat-interpolation
    - mbtiles

executables:
  evie:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evie
    - optparse-generic
  migrate:
    main: Main.hs
    source-dirs: app/migrate
    ghc-options: 
    - -Wall 
    - -fwarn-tabs 
    - -fwarn-incomplete-uni-patterns
    default-extensions:     
    - OverloadedStrings
    - CPP
    - LambdaCase
    dependencies:
    - base64-bytestring
    - bytestring
    - cryptohash
    - directory
    - postgresql-simple
    - postgresql-simple-migration
    - time
    - text