name:                planning-scenario-viewer
version:             0.1.0.0
github:              "state-machine-io/planning-scenario-viewer"
license:             "GPL-3.0"
author:              "State Machine Pty Ltd"
maintainer:          "developers@statemachine.io"
copyright:           "2019 State Machine Pty Ltd"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/state-machine-io/planning-scenario-viewer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant-server
    - wai
    - warp
    - open-browser
    - optparse-generic
    - bytestring
    - text
    - aeson
    - mtl
    - resource-pool
    - postgresql-simple

executables:
  planning-scenario-viewer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - planning-scenario-viewer
    - optparse-generic
